# Generated by Django 5.2.1 on 2025-06-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('grade_engagement', models.CharField(blank=True, max_length=100, null=True)),
                ('date_engagement', models.DateField(blank=True, null=True)),
                ('grade_actuel', models.CharField(blank=True, max_length=100, null=True)),
                ('date_derniere_promotion', models.DateField(blank=True, null=True)),
                ('etat_civil', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_conjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('entite', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_etudes', models.CharField(blank=True, max_length=100, null=True)),
                ('option', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('date_affectation', models.DateField(blank=True, null=True)),
                ('annee_affectation', models.IntegerField(blank=True, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('date_prise_fonction', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=100, null=True)),
                ('date_statut', models.DateField(blank=True, null=True)),
                ('telephone1', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('parcours_professionnel', models.TextField(blank=True, null=True)),
                ('formations_suivies', models.TextField(blank=True, null=True)),
                ('besoin_en_formation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
