# Generated by Django 4.2.23 on 2025-08-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_employe_entite_alter_employe_grade_actuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date_fin_disponibilite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
