# Generated by Django 4.2.23 on 2025-08-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_employe_date_fin_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date_fin_detachement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
