services:
  - type: web
    name: gestion-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn gestion_agent.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gestion_agent.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
